use tgw;
create table tgw_same_list(
    sid int primary key auto_increment,
    img_url varchar(255),
    title varchar(128),
    price decimal(10,2)
);
insert into tgw_same_list values
(null,"image/images/tongleichongwu/78.jpg","【cku认证犬舍】精品比熊犬繁殖基地",1300),
(null,"image/images/tongleichongwu/79.jpg","【cku认证犬舍】精品边牧犬繁殖基地",3200),
(null,"image/images/tongleichongwu/80.jpg","【cku认证犬舍】精品雪纳瑞犬繁殖基地",3100),
(null,"image/images/tongleichongwu/81.jpg","【cku认证犬舍】精品贵宾犬繁殖基地",4000),
(null,"image/images/tongleichongwu/82.jpg","【cku认证犬舍】精品德牧犬繁殖基地",1550),
(null,"image/images/tongleichongwu/83.jpg","【cku认证犬舍】精品维兹拉犬繁殖基地",5400),
(null,"image/images/tongleichongwu/91.jpg","【cku认证犬舍】精品金毛犬繁殖基地",3100),
(null,"image/images/tongleichongwu/92.jpg","【cku认证犬舍】精品苏格兰犬繁殖基地",1200),
(null,"image/images/tongleichongwu/93.jpg","【cku认证犬舍】精品萨摩耶犬繁殖基地",5200),
(null,"image/images/tongleichongwu/94.jpg","【cku认证犬舍】精品贵宾犬繁殖基地",5600),
(null,"image/images/tongleichongwu/95.jpg","【cku认证犬舍】精品柯基犬繁殖基地",1200),
(null,"image/images/tongleichongwu/96.jpg","【cku认证犬舍】精品松狮犬繁殖基地",6100),
(null,"image/images/tongleichongwu/97.jpg","【cku认证犬舍】精品库瓦兹犬繁殖基地",1000),
(null,"image/images/tongleichongwu/98.jpg","【cku认证犬舍】精品泰迪犬繁殖基地",1300),
(null,"image/images/tongleichongwu/99.jpg","【cku认证犬舍】精品粗毛牧羊犬繁殖基地",560),
(null,"image/images/tongleichongwu/100.jpg","【cku认证犬舍】精品萨摩耶犬繁殖基地",1350),
(null,"image/images/tongleichongwu/101.jpg","【cku认证犬舍】精品拉布拉多犬繁殖基地",2100),
(null,"image/images/tongleichongwu/102.jpg","【cku认证犬舍】精品边境犬繁殖基地",3200),
(null,"image/images/tongleichongwu/103.jpg","【cku认证犬舍】精品萨科克斯犬繁殖基地",3100),
(null,"image/images/tongleichongwu/104.jpg","【cku认证犬舍】精品比利猎犬繁殖基地",3100),
(null,"image/images/tongleichongwu/105.jpg","【cku认证犬舍】精品法兰西犬繁殖基地",450),
(null,"image/images/tongleichongwu/106.jpg","【cku认证犬舍】精品挪威那犬繁殖基地",3600),
(null,"image/images/tongleichongwu/107.jpg","【cku认证犬舍】精品大瑞士山地犬犬繁殖基地",650),
(null,"image/images/tongleichongwu/109.jpg","【cku认证犬舍】精品硬毛猎狐繁殖基地",6500),
(null,"image/images/tongleichongwu/110.jpg","【cku认证犬舍】精品中国冠毛犬繁殖基地",3400),
(null,"image/images/tongleichongwu/111.jpg","【cku认证犬舍】精品杜高犬繁殖基地",3400),
(null,"image/images/tongleichongwu/112.jpg","【cku认证犬舍】精品英国斗牛犬繁殖基地",1300),
(null,"image/images/tongleichongwu/113.jpg","【cku认证犬舍】精品多伯曼犬繁殖基地",650),
(null,"image/images/tongleichongwu/114.jpg","【cku认证犬舍】精品波兰低地牧羊犬犬繁殖基地",500),
(null,"image/images/tongleichongwu/115.jpg","【cku认证犬舍】精品蝶耳犬繁殖基地",450),
(null,"image/images/tongleichongwu/116.jpg","【cku认证犬舍】精品西伯利亚雪橇犬犬繁殖基地",1600),
(null,"image/images/tongleichongwu/117.jpg","【cku认证犬舍】精品美国玩具梗繁殖基地",1500),
(null,"image/images/tongleichongwu/118.jpg","【cku认证犬舍】精品诺福克繁殖基地",1500)